cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: game-go
    region:
      static: ap-northeast-2

spring:
  datasource:
    url: jdbc:mariadb://gamego.c9d71oyl8as0.ap-northeast-2.rds.amazonaws.com:3306/gamego?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
    username: root
    password: lsh6451217
    driver-class-name: org.mariadb.jdbc.Driver


#  redis:
#    host: localhost
#    password:
#    port: 6379
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1


  jpa:
    properties:
      hibernate:
        format_sql: true
        open-in-view: false


    hibernate:
      ddl-auto: update
    generate-ddl: true
  profiles:
    include: jwt

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
