jwt:
  secret: Snd0QVBJU2VydmljZUFuZFdlYlNvY2tldFByb2plY3Q= #JwtAPIServiceAndWebSocketProject

  access:
    expiration: 80 #3600*24
    header: Authorization

  refresh:
    expiration: 1600 #3600*24*7
    header: Authorization_refresh